kind: pipeline
name: jython-arm

steps:
- name: clone-jython
  image: drone/git
  commands:
  - git clone https://github.com/jythontools/jython

- name: build-jython
# - name: build-jython-dev
  image: arm32v7/openjdk:7
  commands:
  - apt update
  - apt -y install ant
  - cd jython
  - ant jar-standalone
  # - ant developer-build
  - ls -la dist/

# - name: build-jython-jar-standalone
#   image: arm32v7/openjdk:7
#   commands:
#   - apt update
#   - apt -y install ant
#   - cd jython
#   - ant 
#   - ls -laR ./dist

# - name: publish-jython
#   image: plugins/github-release
#   settings:
#     api_key: xxxxxxxx
#     files:
#       - dist/*
#       - bin/binary.exe
#    checksum:
#       - sha512
#   when:
#     event: tag