kind: pipeline
name: jython-arm

steps:
- name: clone-jython
  image: drone/git
  commands:
  - git clone https://github.com/jythontools/jython

- name: build-jython
  image: arm32v7/openjdk:7
  commands:
  - apt update
  - apt -y install ant
  - cd jython
  - ant all-jars
  #- ant developer-build
  - ls -la dist/

# - name: test-jython
#   image: arm32v7/openjdk:7
#   commands:
#   - apt update
#   - apt -y install ant hg
#   - cd jython
#   - ant all-jars
#   - ls -laR ./dist

# - name: publish-jython
#   image: plugins/github-release
#   settings:
#     api_key: xxxxxxxx
#     files:
#       - dist/*
#       - bin/binary.exe
#    checksum:
#       - md5
#       - sha1
#       - sha256
#       - sha512
#       - adler32
#       - crc32
#   when:
#     event: tag