kind: pipeline
name: jython-arm

# I should upgrade this to publish all jars, once the timeout has been set to two hours

steps:
- name: clone-jython
  image: drone/git
  commands:
  - git clone https://github.com/jythontools/jython
- name: build-jython-standalone
  image: arm32v7/openjdk:7
  commands:
  - apt update
  - apt -y install ant
  - cd jython
  - ant installer
  - ls -laR ./dist
- name: publish-jython-release
  image: plugins/github-release
  settings:
    api_key: 53f03420ac6224c4946fd44b50135c3b46322786
    files:
    - jython/dist/jython-standalone.jar
    checksum:
    - sha512
    title: Jython-2.7.2a.${DRONE_COMMIT_SHA}
  # when:
  #   event: tag